version: "3.7"
services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend-dev
    ports:
      - "8000:8000"
    environment:
      - RELOAD=True
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: fastapi-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - "5555:5432"
    volumes:
      - fastapi-db:/var/lib/postgresql/data

volumes:
  fastapi-db: