version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:14-alpine
    container_name: fastapi-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5555:5432"
    volumes:
      - fastapi-db:/var/lib/postgresql/data
volumes:
  fastapi-db: